name: Build dev container image tagged with latest version and short commit hash

on:
  push:
    branches:
      - "master"

env:
  IMAGE_NAME: ghcr.io/ternaustralia/linkeddata-site

jobs:
  test:
    uses: ternaustralia/linkeddata-site/.github/workflows/test.yml@master

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          # Required by WyriHaximus/github-action-get-previous-tag
          fetch-depth: 0

      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: "0.1.0"

      - name: Tag starts with v
        id: tag-starts-with-v
        if: ${{ startsWith(steps.latest-tag.outputs.tag, 'v') }}
        uses: mad9000/actions-find-and-replace-string@2
        with: 
          source: ${{ steps.latest-tag.outputs.tag }}
          find: 'v'
          replace: ''

      - name: Tag value
        id: tag-value
        uses: haya14busa/action-cond@v1
        with:
          cond: ${{ startsWith(steps.latest-tag.outputs.tag, 'v') }}
          if_true: ${{ steps.tag-starts-with-v.outputs.value }}
          if_false: ${{ steps.latest-tag.outputs.tag }}

      - name: Get git commit hash
        id: hash
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=sha

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.tag-value.outputs.value }}-${{ steps.hash.outputs.version }}
          labels: ${{ steps.metadata.outputs.labels }}
