name: Build dev container image tagged with latest version and short commit hash

on:
  push:
    branches:
      - "master"

env:
  IMAGE_NAME: ghcr.io/ternaustralia/linkeddata-site

jobs:
  test:
    uses: ternaustralia/linkeddata-site/.github/workflows/test.yml@master

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          # Required by WyriHaximus/github-action-get-previous-tag
          fetch-depth: 0

      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: "0.1.0"

      - name: Get semver from latest tag
        id: semver
        uses: LykkeBusiness/get-semver-from-tag-action@v1.0.2
        with:
          tag: ${{ steps.latest-tag.outputs.tag }}

      - name: Get git commit hash
        id: hash
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=sha

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.semver.outputs.non-prefixed }}-${{ steps.hash.outputs.version }}
          labels: ${{ steps.metadata.outputs.labels }}
