name: Build dev container image tagged with latest version and short commit hash

on:
  push:
    branches:
      - "main"

env:
  IMAGE_NAME: ghcr.io/ternaustralia/linkeddata-site

jobs:
  test:
    uses: ternaustralia/linkeddata-site/.github/workflows/test.yml@main

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          # Required by WyriHaximus/github-action-get-previous-tag
          fetch-depth: 0

      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: "0.1.0"

      - name: Tag starts with v
        id: tag-starts-with-v
        if: ${{ startsWith(steps.latest-tag.outputs.tag, 'v') }}
        uses: mad9000/actions-find-and-replace-string@2
        with:
          source: ${{ steps.latest-tag.outputs.tag }}
          find: "v"
          replace: ""

      - name: Tag value
        id: tag-value
        uses: haya14busa/action-cond@v1
        with:
          cond: ${{ startsWith(steps.latest-tag.outputs.tag, 'v') }}
          if_true: ${{ steps.tag-starts-with-v.outputs.value }}
          if_false: ${{ steps.latest-tag.outputs.tag }}

      - name: Get next semver patch version
        id: patch
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.tag-value.outputs.value }}

      - name: Get git commits since last tag
        id: commitscount
        run: echo "value=$(git rev-list `git rev-list --tags --no-walk --max-count=1`..HEAD --count)" >> $GITHUB_OUTPUT

      - name: Get git commit hash
        id: commit-hash
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=sha

      - name: Rename git commit hash
        id: hash
        uses: mad9000/actions-find-and-replace-string@2
        with:
          source: ${{ steps.commit-hash.outputs.version }}
          find: "sha-"
          replace: dev.${{ steps.commitscount.outputs.value }}.

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up and use Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build dev container image and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.patch.outputs.patch }}-${{ steps.hash.outputs.value }}
          build-args: |
            REACT_APP_GIT_VERSION=${{ steps.patch.outputs.patch }}-${{ steps.hash.outputs.value }}

      - name: Rename tag with local
        id: local-tag
        uses: mad9000/actions-find-and-replace-string@2
        with:
          source: ${{ steps.hash.outputs.value }}
          find: "dev"
          replace: "local"

      - name: Build local container image and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.patch.outputs.patch }}-${{ steps.local-tag.outputs.value }}
          build-args: |
            REACT_APP_GIT_VERSION=${{ steps.patch.outputs.patch }}-${{ steps.local-tag.outputs.value }}
