name: Build dev container image tagged with latest version and short commit hash

on:
  push:
    branches:
      - "master"

env:
  IMAGE_NAME: ghcr.io/ternaustralia/linkeddata-site

jobs:
  test:
    uses: ternaustralia/linkeddata-site/.github/workflows/test.yml@master
    
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: "0.1.0"

      - name: Get git commit hash
        id: hash
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=sha

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.latest-tag.outputs.tag }}-${{ steps.hash.outputs.labels.org.opencontainers.image.version }}
          labels: ${{ steps.metadata.outputs.labels }}
