name: Build release container image tagged with release version and push to GitHub Container Registry

on:
  release:
    types: [published]

env:
  IMAGE_NAME: ghcr.io/ternaustralia/linkeddata-site

jobs:
  test:
    uses: ternaustralia/linkeddata-site/.github/workflows/test.yml@main

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=semver,pattern={{version}}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          build-args: |
            REACT_APP_GIT_VERSION=${{ steps.metadata.outputs.version }}
          labels: ${{ steps.metadata.outputs.labels }}
